<?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('content'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>

<?php foreach($messages as $message): ?>
    <div>
        <?php echo $message->getCreatedAt()->format('Y-m-d H:i:s'); ?>
        <?php echo $message->getContent(); ?>
    </div>
<?php endforeach; ?>

<script>
    $(function() {
        $('#chat-form').submit(
            function (event) {
                event.preventDefault();
                event.stopPropagation();

                var request = $.ajax({
                    method: "POST",
                    url: "/chat/add",
                    data: { content: "" },
                    dataType: "json"
                });

                request.done(
                    function(response) {
                        console.log(response);
                        console.log(response.one);
                    }
                );
            }
        );
    });
</script>
