<?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('content'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>

<table id="messages-table" style="width:100%">
    <?php echo $this->partial('chat/chat/_messages_table_content', ['messagesData' => $messagesData]); ?>
</table>

<script>
    $(function() {
        $('#chat-form').submit(
            function (event) {
                event.preventDefault();
                event.stopPropagation();

                var request = $.ajax({
                    method: "POST",
                    url: "/chat/add",
                    data: { content: $('#message-content-input').val() },
                    dataType: "html"
                });

                request.done(
                    function(response) {
                        $('#messages-table').html(response);
                        $('#message-content-input').val('');
                    }
                );
            }
        );
    });
</script>
