<div class="row">
    <?php echo $this->form()->openTag($form); ?>
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <div class="input-group">
                <?php echo $this->formRow($form->get('content')); ?>
                <span class="input-group-btn">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </span>
            </div>
        </div>
    <?php echo $this->form()->closeTag(); ?>
</div>

<div class="table-responsive">
    <table id="messages-table" class="table table-striped">
        <?php echo $this->partial('chat/chat/_messages_table_content', ['messagesData' => $messagesData]); ?>
    </table>
</div>

<script>
    $(function() {
        $('#chat-form').submit(
            function (event) {
                event.preventDefault();
                event.stopPropagation();

                var request = $.ajax({
                    method: "POST",
                    url: "<?php echo $this->url('chat', ['action' => 'add']); ?>",
                    data: { content: $('#message-content-input').val() },
                    dataType: "html"
                });

                $('#message-content-input').val('');

                request.done(
                    function(response) {
                        $('#messages-table tr').remove();
                        $('#messages-table').append(response);
                    }
                );
            }
        );
    });
</script>
